Repository leanix/vsm-sbom-booster, pull requests merged in 2023-11, with the labels that each got.

#67 CID-1624: Validate contribution process
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/gradle-build.yml
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: chore

#68 [CID-2087] Generate CycloneDX v1.5 Sbom files
  build.gradle.kts
  src/main/kotlin/net/leanix/vsm/sbomBooster/service/OrtService.kt
Labels: enhancement

#70 v1.3.0 release
  build.gradle.kts
Labels: minor
